#!/bin/sh /etc/rc.common
# seamless-wan: procd service for WiFi roaming daemon
START=98
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /opt/wifi-roaming.sh daemon
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
